// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Class_Lib;

#nullable disable

namespace Class_Lib.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250409230520_Test-1")]
    partial class Test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Class_Lib.Backend.Delivery_vehicles.DeliveryVehicle", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MaxStorageCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MaxVolume")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("DeliveryVehicles");
                });

            modelBuilder.Entity("Class_Lib.BaseLocation", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GeoDataLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("GeoDataLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("WarehouseType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GeoDataLongitude", "GeoDataLatitude");

                    b.ToTable("Locations");

                    b.HasDiscriminator<string>("WarehouseType").HasValue("BaseLocation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Class_Lib.Content", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PackageID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name", "PackageID");

                    b.HasIndex("PackageID");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("Class_Lib.Coordinates", b =>
                {
                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Longitude", "Latitude");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("Class_Lib.Country", b =>
                {
                    b.Property<string>("ISO2Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISO2Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ISO2Code = "UA",
                            FullName = "Ukraine"
                        },
                        new
                        {
                            ISO2Code = "PL",
                            FullName = "Poland"
                        },
                        new
                        {
                            ISO2Code = "RO",
                            FullName = "Romania"
                        });
                });

            modelBuilder.Entity("Class_Lib.Package", b =>
                {
                    b.Property<uint>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentLocationLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentLocationLongitude")
                        .HasColumnType("REAL");

                    b.Property<uint?>("DeliveryVehicleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ReceiverID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SenderID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SentFromID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SentToID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("WarehouseID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageID");

                    b.HasIndex("DeliveryVehicleID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.HasIndex("SentFromID");

                    b.HasIndex("SentToID");

                    b.HasIndex("WarehouseID");

                    b.HasIndex("CurrentLocationLongitude", "CurrentLocationLatitude");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Class_Lib.PackageEvent", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PackageID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LocationLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("LocationLongitude")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp", "PackageID");

                    b.HasIndex("PackageID");

                    b.HasIndex("LocationLongitude", "LocationLatitude");

                    b.ToTable("PackageEvents");
                });

            modelBuilder.Entity("Class_Lib.Person", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Clients");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Class_Lib.Warehouse", b =>
                {
                    b.HasBaseType("Class_Lib.BaseLocation");

                    b.Property<bool>("IsAutomated")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MaxStorageCapacity")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Warehouse");
                });

            modelBuilder.Entity("Class_Lib.Employee", b =>
                {
                    b.HasBaseType("Class_Lib.Person");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("WorkplaceID")
                        .HasColumnType("INTEGER");

                    b.HasIndex("WorkplaceID");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("Class_Lib.PostalOffice", b =>
                {
                    b.HasBaseType("Class_Lib.Warehouse");

                    b.Property<bool>("HandlesPublicDropOffs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegionalHQ")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("PostalOffice");
                });

            modelBuilder.Entity("Class_Lib.BaseLocation", b =>
                {
                    b.HasOne("Class_Lib.Coordinates", "GeoData")
                        .WithMany()
                        .HasForeignKey("GeoDataLongitude", "GeoDataLatitude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoData");
                });

            modelBuilder.Entity("Class_Lib.Content", b =>
                {
                    b.HasOne("Class_Lib.Package", "Package")
                        .WithMany("DeclaredContent")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Class_Lib.Package", b =>
                {
                    b.HasOne("Class_Lib.Backend.Delivery_vehicles.DeliveryVehicle", null)
                        .WithMany("Packages")
                        .HasForeignKey("DeliveryVehicleID");

                    b.HasOne("Class_Lib.Backend.Delivery_vehicles.DeliveryVehicle", null)
                        .WithMany("StoredPackages")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Class_Lib.Person", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Class_Lib.Person", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Class_Lib.Warehouse", "SentFrom")
                        .WithMany("StoredPackages")
                        .HasForeignKey("SentFromID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Class_Lib.Warehouse", "SentTo")
                        .WithMany()
                        .HasForeignKey("SentToID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Class_Lib.Warehouse", null)
                        .WithMany("Packages")
                        .HasForeignKey("WarehouseID");

                    b.HasOne("Class_Lib.Coordinates", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationLongitude", "CurrentLocationLatitude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentLocation");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("SentFrom");

                    b.Navigation("SentTo");
                });

            modelBuilder.Entity("Class_Lib.PackageEvent", b =>
                {
                    b.HasOne("Class_Lib.Package", "Package")
                        .WithMany("Log")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Class_Lib.Coordinates", "Location")
                        .WithMany()
                        .HasForeignKey("LocationLongitude", "LocationLatitude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Class_Lib.Employee", b =>
                {
                    b.HasOne("Class_Lib.BaseLocation", "Workplace")
                        .WithMany("Staff")
                        .HasForeignKey("WorkplaceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Class_Lib.Backend.Delivery_vehicles.DeliveryVehicle", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("StoredPackages");
                });

            modelBuilder.Entity("Class_Lib.BaseLocation", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Class_Lib.Package", b =>
                {
                    b.Navigation("DeclaredContent");

                    b.Navigation("Log");
                });

            modelBuilder.Entity("Class_Lib.Warehouse", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("StoredPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
