// <auto-generated />
using System;
using Class_Lib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Class_Lib.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250430063815_FlattenedEmployee")]
    partial class FlattenedEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Class_Lib.Backend.Person_related.Client", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Class_Lib.Backend.Person_related.User", b =>
                {
                    b.Property<long>("PersonID")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PersonID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Class_Lib.BaseLocation", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<double>("GeoDataLatitude")
                        .HasColumnType("float");

                    b.Property<double>("GeoDataLongitude")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("GeoDataLongitude", "GeoDataLatitude");

                    b.ToTable("Locations", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Class_Lib.Content", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("PackageID")
                        .HasColumnType("bigint");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Name", "PackageID");

                    b.HasIndex("PackageID");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Class_Lib.Coordinates", b =>
                {
                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Longitude", "Latitude");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("Class_Lib.Employee", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkplaceID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WorkplaceID");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Class_Lib.Package", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CurrentLocationID")
                        .HasColumnType("bigint");

                    b.Property<long>("PackageID")
                        .HasColumnType("bigint");

                    b.Property<int>("PackageStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("ReceiverID")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SenderID")
                        .HasColumnType("bigint");

                    b.Property<long>("SentFromID")
                        .HasColumnType("bigint");

                    b.Property<long>("SentToID")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long?>("WarehouseID")
                        .HasColumnType("bigint");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("CurrentLocationID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.HasIndex("SentFromID");

                    b.HasIndex("SentToID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Class_Lib.PackageEvent", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("PackageID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LocationID")
                        .HasColumnType("bigint");

                    b.HasKey("Timestamp", "PackageID");

                    b.HasIndex("LocationID");

                    b.HasIndex("PackageID");

                    b.ToTable("PackageEvents");
                });

            modelBuilder.Entity("Class_Lib.Warehouse", b =>
                {
                    b.HasBaseType("Class_Lib.BaseLocation");

                    b.Property<bool>("IsAutomated")
                        .HasColumnType("bit");

                    b.Property<long>("MaxStorageCapacity")
                        .HasColumnType("bigint");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("Class_Lib.PostalOffice", b =>
                {
                    b.HasBaseType("Class_Lib.Warehouse");

                    b.Property<bool>("HandlesPublicDropOffs")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegionalHQ")
                        .HasColumnType("bit");

                    b.ToTable("PostalOffices", (string)null);
                });

            modelBuilder.Entity("Class_Lib.Backend.Person_related.User", b =>
                {
                    b.HasOne("Class_Lib.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("Class_Lib.Backend.Person_related.User", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Class_Lib.BaseLocation", b =>
                {
                    b.HasOne("Class_Lib.Employee", null)
                        .WithMany("ManagedLocations")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("Class_Lib.Coordinates", "GeoData")
                        .WithMany()
                        .HasForeignKey("GeoDataLongitude", "GeoDataLatitude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoData");
                });

            modelBuilder.Entity("Class_Lib.Content", b =>
                {
                    b.HasOne("Class_Lib.Package", "Package")
                        .WithMany("DeclaredContent")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Class_Lib.Employee", b =>
                {
                    b.HasOne("Class_Lib.BaseLocation", "Workplace")
                        .WithMany("Staff")
                        .HasForeignKey("WorkplaceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Class_Lib.Package", b =>
                {
                    b.HasOne("Class_Lib.BaseLocation", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Class_Lib.Backend.Person_related.Client", "Receiver")
                        .WithMany("PackagesReceived")
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Class_Lib.Backend.Person_related.Client", "Sender")
                        .WithMany("PackagesSent")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Class_Lib.Warehouse", "SentFrom")
                        .WithMany("PackagesSentFromHere")
                        .HasForeignKey("SentFromID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Class_Lib.Warehouse", "SentTo")
                        .WithMany("PackagesSentToHere")
                        .HasForeignKey("SentToID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Class_Lib.Warehouse", null)
                        .WithMany("StoredPackages")
                        .HasForeignKey("WarehouseID");

                    b.Navigation("CurrentLocation");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("SentFrom");

                    b.Navigation("SentTo");
                });

            modelBuilder.Entity("Class_Lib.PackageEvent", b =>
                {
                    b.HasOne("Class_Lib.BaseLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Class_Lib.Package", "Package")
                        .WithMany("Log")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Class_Lib.Warehouse", b =>
                {
                    b.HasOne("Class_Lib.BaseLocation", null)
                        .WithOne()
                        .HasForeignKey("Class_Lib.Warehouse", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Class_Lib.PostalOffice", b =>
                {
                    b.HasOne("Class_Lib.Warehouse", null)
                        .WithOne()
                        .HasForeignKey("Class_Lib.PostalOffice", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Class_Lib.Backend.Person_related.Client", b =>
                {
                    b.Navigation("PackagesReceived");

                    b.Navigation("PackagesSent");
                });

            modelBuilder.Entity("Class_Lib.BaseLocation", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Class_Lib.Employee", b =>
                {
                    b.Navigation("ManagedLocations");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Class_Lib.Package", b =>
                {
                    b.Navigation("DeclaredContent");

                    b.Navigation("Log");
                });

            modelBuilder.Entity("Class_Lib.Warehouse", b =>
                {
                    b.Navigation("PackagesSentFromHere");

                    b.Navigation("PackagesSentToHere");

                    b.Navigation("StoredPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
